### ISSUE TITLE
Support for dependency/prerequisite jobs similar to a Makefile

### ISSUE THREAD

**Issue by MattyRad** [jacobdeichert/mask#113]
Hi, this looks great!

Full candor, I haven't actually tried mask yet, but I've gone through the Readme and the only hesitation I have before completely jumping on board is that I don't see support for dependency/prerequisite jobs (similar to [Makefile prerequisites](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html)). Are there any tricks for deduplicating commands, or would it be a good future enhancement?

**Comment by jacobdeichert** [comment]
👋 Hey @MattyRad 

If I understand correctly, it sounds like you want to define a mask command that automatically runs other mask commands as a prerequisite, before running its own logic. Is that right?

We don't have a single one-liner way to do that. But if your command is using a shell lang, then running other commands is very straightforward with the `$MASK` helper alias.

~~~bash
# run some prereqs
$MASK some_command
$MASK another_command
# rest of script here...
~~~

**Comment by MattyRad** [comment]
Yeah that makes sense, seems obvious is retrospect. Thanks!
