### ISSUE TITLE
Support optional (non-required) positional arguments

### ISSUE THREAD

**Issue by jacobdeichert** [jacobdeichert/mask#5]
Required arguments use the round brackets like `(required_arg)` so optional args can probably use square brackets `[optional_arg]`.

```md
## say [phrase]

~~~sh
if [[ $phrase != "" ]]; then
    echo "$phrase"
else
    echo "😶"
fi
~~~
```

**Comment by jakedeichert** [comment]
I'll take this one sometime this week.

**Comment by brandonkal** [comment]
I would suggest `(arg_name?)` where the question denotes optional, much like in TypeScript types.

**Comment by jakedeichert** [comment]
Hmmm, i like that idea. That would make it very easy to tell what's optional and what's not.

**Comment by kivio** [comment]
it will be good if we can provide default value

**Comment by falky97** [comment]
I would suggest following traditional shell syntax for brackets: <required> [optional]

**Comment by jakedeichert** [comment]
> I would suggest following traditional shell syntax for brackets: [optional]

Yeah, agree that sticking with traditional shell syntax is better – going to go with [optional] instead of (optional?) 👍

**Comment by jakedeichert** [comment]
> it will be good if we can provide default value

Maybe like this: `[optional=default_value]`  ?

**Comment by falky97** [comment]
Could also do traditional shell syntax for mandatory args: `<required>` as opposed to current `(required)`

**Comment by jakedeichert** [comment]
> Could also do traditional shell syntax for mandatory args: `<required>` as opposed to current `(required)`


Yeah, I originally had that but then changed it in #16 because a few markdown renderers I noticed were interpreting `<required>` args as html :/

I might have to take another look at that and see which renderers (like GitHub, or VS Code markdown preview) break... can't remember off the top of my head.

**Comment by falky97** [comment]
> Maybe like this: [optional=default_value]?

> If we add it here, we should add to named flags as well.

These both make sense. Just make sure to only set default values for optional args not required ones!
