### ISSUE TITLE
Support for musl

### ISSUE THREAD

**Issue by 8Mobius8** [jacobdeichert/mask#93]
Add support for `musl` linked executable for distributions that use it (ie. Alpine). I would think this would be done by adding another asset on release that would be named 
`mask-vX.XX.X-x86_64-unknown-linux-musl.zip` or something like it.

I have limited knowledge of rust, but seems like this could be achieved by adding another release job in `.github/workflows/release.yml` that could make use of an Alpine to build and target. I believe `cargo` needs use the target `x86_64-unknown-linux-musl`.

**Comment by 8Mobius8** [comment]
@jacobdeichert If you don't mind I would like to attempt the suggestion above.

I believe I should be able to test this out on a fork of this repo without affecting this one.

I will say this will be my first foray into github actions, so any advice would be welcome.

**Comment by jacobdeichert** [comment]
@8Mobius8 that would be great!

Yes, modifying [release.yml](https://github.com/jacobdeichert/mask/blob/master/.github/workflows/release.yml) is all you need to do I think. 

I'd copy/paste the `release-linux` block, name the new one `release-linux-musl` and then figure out how to tell cargo to build it for musl. My memory is a bit fuzzy on compiling for musl, but I think you can probably still use `runs-on: ubuntu-latest` and it should let you cross-compile to musl. Or, GitHub might support alpine runners, so up to you if that's easier.

**Comment by jacobdeichert** [comment]
@8Mobius8 just a heads up that I released v0.11.3

You can find the musl binary attached here:
https://github.com/jacobdeichert/mask/releases/tag/v0.11.3
