### ISSUE TITLE
Be able to inline Rust?

### ISSUE THREAD

**Issue by brandonros** [jacobdeichert/mask#98]
```
# Tasks For My Project


<!-- A heading defines the command's name -->
## build

<!-- A blockquote defines the command's description -->
> Builds my project

<!-- A code block defines the script to be executed -->
~~~rust
fn main() {
  println!("Hello, world!");
}
~~~
```

```
$ mask build
ERROR: No such file or directory (os error 2)
```

**Comment by brandonros** [comment]
Looks like I can `sh` https://rust-script.org/

**Comment by jacobdeichert** [comment]
Hey! Sorry, I currently don't have plans to support any compiled languages for now. 

The various supported scripting runtimes cover 99% of use cases people expect in mask as a command runner. 

I'm glad to see rust-script exists to fill this use case though!
